#!/bin/sh

gitrs="cargo run"

rm -rf repo
mkdir repo
cd repo

$gitrs init
$gitrs config --add user.name "John Doe"
$gitrs config --add user.email "john.doe@something.com"
echo "hello world!" > hello
$gitrs add hello
$gitrs commit "initial commit"
