#!/bin/sh

gitrs="cargo run"

rm -rf repo
rm -rf copy

$gitrs init repo
cd repo
$gitrs config --add user.name "John Doe"
$gitrs config --add user.email "john.doe@something.com"

echo 'Hello world!' > file_a
$gitrs status
$gitrs add file_a
$gitrs commit -m "first commit"

cd ..
$gitrs clone repo copy
cp repo/.git/config copy/.git/config
cd copy
echo 'new file' > file_b
$gitrs add file_b
$gitrs commit -m "second commit"

cd ../repo
$gitrs remote add copy_remote ../copy
$gitrs branch new_b
$gitrs pull copy_remote master

$gitrs checkout new_b
echo 'new line' >> file_a
$gitrs status
$gitrs diff
$gitrs add file_a
$gitrs commit -m "third commit"
$gitrs checkout master
$gitrs merge new_b
